name: Docker

on:
  schedule:
    - cron: '33 15 * * *'
  push:
    branches: [ "latest" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "latest" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/takermanltd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.REGISTRY_TOKEN}}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Auth NuGet
        run: | 
          dotnet nuget add source https://nuget.pkg.github.com/takermanltd/index.json \
            --name github \
            --username takerman \
            --password ${{secrets.REGISTRY_TOKEN}} \
            --configfile takerman.portfolio.client/nuget.config
        
      - name: Restore NuGet Packages
        run: dotnet restore Takerman.Portfolio.sln
        
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}